### ISSUE TITLE
Missing ghgv.json

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#74]
After fixing #73 , the next error comes from ghgvcR: the file `tmp/out/ghgv.json` is not found.

```
Output from R script is:

Completed 500 Internal Server Error in 29ms

Errno::ENOENT (No such file or directory - /usr/local/ghgvc-development/ghgvc/tmp/out/ghgv.json):
  app/controllers/workflows_controller.rb:133:in `read'
  app/controllers/workflows_controller.rb:133:in `create_config_input'
```

**Comment by potterzot** [comment]
@dlebauer it looks like maybe /usr/local/ghgvc-development/ghgvc/tmp/out/
doesn't exist?

ghgv.json is written by the calc_ghgvc.R script, and it looks like R can't
find that directory. Hard to tell without seeing it.

---------------------
Nicholas Potter
http://potterzot.com

**Comment by gsrohde** [comment]
@potterzot `/usr/local/ghgvc-development/ghgvc/tmp/out/` _does_ exist.  Just to clarify, the pin drops now work (though after about a 4s delay).  The `No such file or directory` doesn't actually occur until you press "Run Calculator".

**Comment by potterzot** [comment]
Should be fixed with [commit 4597fa0](https://github.com/ebimodeling/ghgvcR/commit/4597fa04bfe31149cd0f5984c7c28578767ee236) now. The biome() function in ghgvcR was erroneously creating "native_eco" as an option instead of saving those values to the "native_eco" ecosystems. There should never be an native_eco option to select.

Fingers crossed...

**Comment by gsrohde** [comment]
@potterzot I updated the ghgvcR tree, but I still get the `No such file or directory - /usr/local/ghgvc-development/ghgvc/tmp/out/ghgv.json` error (and the application hangs) when I press "Run Calculator".

**Comment by potterzot** [comment]
You'd have to do a build again: `R CMD INSTALL ghgvcR` or something like
that.

---------------------
Nicholas Potter
http://potterzot.com

**Comment by gsrohde** [comment]
Good catch.  But I tried this and I still get the same error.

**Comment by potterzot** [comment]
Hi Scott - I haven't forgotten about this, I just have an imminent
deadline. I'll try to look at it this evening.

---------------------
Nicholas Potter
http://potterzot.com

**Comment by potterzot** [comment]
@dlebauer @gsrohde I spent some time looking into this over the weekend, and I can't reproduce this bug on my side. Even if I delete the ghgv.json file, it gets recreated when I run the app. A few ideas on what could be going on:

**1. The latest ghgvcR package is not installed or not being called**
The `ghgvc()` function by default saves it's output to a file called "ghgv.json", the missing file in this bug. If you open R and do:
``` {r}
library(ghgvcr)
help(ghgvc)
```
does the help file indicate that the "output_filename" parameter is "ghgv"? 

If yes, then this is not the problem.

**2. The app is not passing the correct location to the calc_ghgvc.R script**
Is the value of `@rscript_outdir` as set in `line 59` of workflows_controller.rb set to the correct directory? From the error, it looks like it should resolve to `/usr/local/ghgvc-development/ghgvc/tmp/out/`.

If that looks right, then this isn't the problem either.

**3. Some other issue that I haven't figured out**
A few options then:

* We could try to work through it together on the phone.

* You could zip ghgvc and ghgvcR up and send it to me so I can install on my machine and see if I can replicate the error.

* You could send me the "log/development.log" file that hopefully contains some more information.

* You could set up a live example and I will take a look at the error codes printed to the javascript console.

* You could give me temporary access to your server and I can take a look at the setup and see if I can figure out what is going wrong.

Other than that I'm sort of at a loss, but I'm happy to move forward in whatever fashion you both think would be most helpful in getting things up and running.

**Comment by dlebauer** [comment]
@potterzot I can give you access to pecandev, but the important thing is that ghgvc can be configured on any server - so if you can test it on either a CentOS or Ubuntu VM that would be great. The https://github.com/ebimodeling/ghgvc/blob/master/ghgvc.sh script should automate the install (or at least get you most of the way there; will probably need at least to add download of the saatchi.nc file dependency).

Could you go forward testing this out on a fresh CentOS or Ubuntu VM?

**Comment by potterzot** [comment]
@dlebauer Sure, that sounds like a good option, and will allow me to
document the steps to update the script and install readme.

---------------------
Nicholas Potter
http://potterzot.com

@potterzot <https://github.com/potterzot> I can give you access to
pecandev, but the important thing is that ghgvc can be configured on any
server - so if you can test it on either a CentOS or Ubuntu VM that would
be great. The https://github.com/ebimodeling/ghgvc/blob/master/ghgvc.sh
script should automate the install (or at least get you most of the way
there; will probably need at least to add download of the saatchi.nc file
dependency).

Could you go forward testing this out on a fresh CentOS or Ubuntu VM?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/ebimodeling/ghgvc/issues/74#issuecomment-199371062>

**Comment by potterzot** [comment]
@dlebauer and @gsrohde, here is a [working example](http://ec2-52-38-133-219.us-west-2.compute.amazonaws.com/).

I've added an INSTALL.md file to ghgvc development branch, and also updated the ghgvc.sh install script to work with CentOS.

I found the problem iin the nginx logs, which was a missing "/" in app/controllers/workflows_controller.rb that only came into play when the server was running in production mode instead of development mode, hence why it was working on my laptop and not on your server I suspect.

Pulling the newest [development branch commit](https://github.com/ebimodeling/ghgvc/commit/1ccb349549f790ba1bb669d3d6e811d2b6243152) should hopefully be enough to fix it.

**Comment by dlebauer** [comment]
Great, but I am not seeing plots or csv downloads .... Are you?

**Comment by potterzot** [comment]
I thought from a previous conversation that the plots had not been working
for some time, before I started. I haven't done any work on either the
plots or the csv part of things, but I'll take a look at it today.

---------------------
Nicholas Potter
http://potterzot.com

**Comment by dlebauer** [comment]
There is a bug (#72) where plots aren't generated if there is only one site
being compared but otherwise the plotting and csv generation works on the
http://www.ecosystemservicescalc.org

**Comment by dlebauer** [comment]
![image](https://cloud.githubusercontent.com/assets/464871/14213463/afa45e5c-f7fd-11e5-8463-828ddb3e7e1c.png)

**Comment by potterzot** [comment]
I see. Thanks I'll look into it.

---------------------
Nicholas Potter
http://potterzot.com

**Comment by potterzot** [comment]
@dlebauer the csv download is working. I've created a separate [issue for the charting](https://github.com/ebimodeling/ghgvc/issues/75). I can continue to work on it, but I *think* that the problem is a javascript problem.

**Comment by potterzot** [comment]
Closing this issue since we have working plots.
